services:
  reverse-proxy:
    image: traefik:v3.1
    container_name: whombat-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whombat-backend
    command: ["whombat"]
    environment:
      - WHOMBAT_DATA_DIR=/data/
      - WHOMBAT_DB_URL=sqlite+aiosqlite:////data/whombat_new.db
      - WHOMBAT_DOMAIN=localhost
      # SSO config
      - WHOMBAT_AZURE_TENANT_ID=a5c5b901-bec1-4679-81ae-99ff93e7d48b
      - WHOMBAT_AZURE_CLIENT_ID=b92d883e-8593-4b69-9689-9a97df34ea20
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/api/v1`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
      - "traefik.http.routers.backend.priority=2"
    volumes:
      - type: volume
        source: db-data
        target: /data
      - type: bind
        source: example_data/
        target: /audio
    networks:
      - public

  frontend:
    build:
      context: front
      args:
        - NODE_ENV=production
    container_name: whombat-frontend
    command: ["npx", "pnpm", "start"]
    environment:
      - NEXT_PUBLIC_BACKEND_HOST=http://localhost/api/v1
      - NEXTAUTH_URL=http://localhost
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.priority=1"
    depends_on:
      - backend
    networks:
      - public

networks:
  public:
  
volumes:
  db-data: