"""Add azure_oid to User

Revision ID: d5b25e3e9866
Revises: a8a44e0eea11
Create Date: 2025-06-03 09:41:14.936206

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5b25e3e9866"
down_revision: Union[str, None] = "a8a44e0eea11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("azure_oid", sa.String(length=128), nullable=True)
    )
    op.create_index(
        op.f("ix_user_azure_oid"), "user", ["azure_oid"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_azure_oid"), table_name="user")
    op.drop_column("user", "azure_oid")
    # ### end Alembic commands ###
